# Generated by Django 5.1.7 on 2025-04-22 12:37

import apps.bookings.models
import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_city", models.CharField(max_length=255)),
                ("to_city", models.CharField(max_length=255)),
                ("departure_date", models.DateField()),
                ("passenger_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("site", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "ticket",
                    models.FileField(
                        storage=apps.bookings.models.TicketFileS3Storage,
                        upload_to=apps.bookings.models.get_tickets_r2_file_path,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
