# Generated by Django 5.1.7 on 2025-04-22 13:50

import apps.bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="ticket",
            field=models.FileField(
                storage=apps.bookings.models.TicketFileS3Storage(),
                upload_to=apps.bookings.models.get_tickets_r2_file_path,
            ),
        ),
    ]
