# Generated by Django 5.1.7 on 2025-04-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="passenger_id",
            field=models.CharField(default="2023.08.272", max_length=255),
            preserve_default=False,
        ),
    ]
