# Generated by Django 5.1.7 on 2025-04-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_passenger_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="passenger_email",
            field=models.CharField(default="erlanerlangg@gmail.com", max_length=255),
            preserve_default=False,
        ),
    ]
