# Generated by Django 5.1.7 on 2025-04-24 04:00

import apps.bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_passenger_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="ticket",
            field=models.FileField(
                null=True,
                storage=apps.bookings.models.TicketFileS3Storage(),
                upload_to=apps.bookings.models.get_tickets_r2_file_path,
            ),
        ),
    ]
